import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";
import request from "supertest";
import express, { Express, Request, Response, NextFunction } from "express";
import session from "express-session";
import { registerRoutes } from "../routes";
import { MemStorage, IStorage } from "../storage";
import http from "http";

vi.mock("openai", () => ({
  default: class MockOpenAI {
    chat = {
      completions: {
        create: vi.fn().mockResolvedValue({
          choices: [{
            message: {
              content: "## Test Policy\n\nThis is a test document generated by AI."
            }
          }]
        })
      }
    };
  }
}));

describe("Onboarding Templates API", () => {
  let app: Express;
  let server: http.Server;
  let storage: IStorage;
  let tenantId: string;
  let userId: string;

  beforeAll(async () => {
    app = express();
    app.use(express.json());
    app.use(session({
      secret: "test-secret",
      resave: false,
      saveUninitialized: true,
    }));
    
    storage = new MemStorage();
    
    const tenant = await storage.createTenant({
      name: "Test Store",
      language: "ru",
      tone: "formal",
      addressStyle: "vy",
      currency: "RUB",
      timezone: "Europe/Moscow",
    });
    tenantId = tenant.id;
    
    const user = await storage.createUser({
      username: "admin",
      password: "password",
      tenantId,
      role: "admin",
    });
    userId = user.id;
    
    app.use((req: Request, _res: Response, next: NextFunction) => {
      (req as any).userId = userId;
      (req as any).isAuthenticated = () => true;
      next();
    });
    
    server = http.createServer(app);
    await registerRoutes(server, app);
  });

  afterAll(() => {
    vi.clearAllMocks();
  });

  describe("POST /api/onboarding/generate-templates", () => {
    it("should generate 4 templates when all options are true", async () => {
      const response = await request(app)
        .post("/api/onboarding/generate-templates")
        .send({
          answers: {
            BUSINESS: { name: "Test Store", description: "A test store" },
            POLICIES: { delivery: "Fast delivery", returns: "Easy returns" },
          },
          options: {
            includeFaq: true,
            includePolicy: true,
            includeDelivery: true,
            includeReturns: true,
          },
        });

      expect(response.status).toBe(200);
      expect(response.body.drafts).toHaveLength(4);
      
      const docTypes = response.body.drafts.map((d: any) => d.docType);
      expect(docTypes).toContain("policy");
      expect(docTypes).toContain("faq");
      expect(docTypes).toContain("delivery");
      expect(docTypes).toContain("returns");
      
      for (const draft of response.body.drafts) {
        expect(draft.title).toBeTruthy();
        expect(draft.content).toBeTruthy();
        expect(draft.docType).toBeTruthy();
      }
    });

    it("should generate only selected templates", async () => {
      const response = await request(app)
        .post("/api/onboarding/generate-templates")
        .send({
          answers: { BUSINESS: { name: "Test Store" } },
          options: {
            includeFaq: true,
            includePolicy: false,
            includeDelivery: false,
            includeReturns: false,
          },
        });

      expect(response.status).toBe(200);
      expect(response.body.drafts).toHaveLength(1);
      expect(response.body.drafts[0].docType).toBe("faq");
    });

    it("should return empty array when no options selected", async () => {
      const response = await request(app)
        .post("/api/onboarding/generate-templates")
        .send({
          answers: { BUSINESS: { name: "Test Store" } },
          options: {
            includeFaq: false,
            includePolicy: false,
            includeDelivery: false,
            includeReturns: false,
          },
        });

      expect(response.status).toBe(200);
      expect(response.body.drafts).toHaveLength(0);
    });
  });

  describe("POST /api/onboarding/apply-templates", () => {
    it("should create knowledge docs from drafts", async () => {
      const drafts = [
        { title: "Test Policy", docType: "policy" as const, content: "Policy content" },
        { title: "Test FAQ", docType: "faq" as const, content: "FAQ content" },
      ];

      const response = await request(app)
        .post("/api/onboarding/apply-templates")
        .send({ drafts });

      expect(response.status).toBe(200);
      expect(response.body.success).toBe(true);
      expect(response.body.createdDocs).toBe(2);
      expect(response.body.documents).toHaveLength(2);
      
      for (const doc of response.body.documents) {
        expect(doc.id).toBeTruthy();
        expect(doc.title).toBeTruthy();
        expect(doc.docType).toBeTruthy();
      }
    });

    it("should reject invalid drafts", async () => {
      const response = await request(app)
        .post("/api/onboarding/apply-templates")
        .send({
          drafts: [
            { title: "", docType: "policy", content: "content" },
          ],
        });

      expect(response.status).toBe(400);
      expect(response.body.error).toBe("Invalid drafts");
    });

    it("should reject invalid docType", async () => {
      const response = await request(app)
        .post("/api/onboarding/apply-templates")
        .send({
          drafts: [
            { title: "Test", docType: "invalid_type", content: "content" },
          ],
        });

      expect(response.status).toBe(400);
      expect(response.body.error).toBe("Invalid drafts");
    });

    it("should reject empty content", async () => {
      const response = await request(app)
        .post("/api/onboarding/apply-templates")
        .send({
          drafts: [
            { title: "Test", docType: "policy", content: "" },
          ],
        });

      expect(response.status).toBe(400);
      expect(response.body.error).toBe("Invalid drafts");
    });
  });

  describe("RBAC", () => {
    it("should reject unauthenticated requests", async () => {
      const unauthApp = express();
      unauthApp.use(express.json());
      unauthApp.use(session({ secret: "test", resave: false, saveUninitialized: true }));
      
      unauthApp.use((req: Request, _res: Response, next: NextFunction) => {
        (req as any).userId = undefined;
        (req as any).isAuthenticated = () => false;
        next();
      });
      
      const unauthServer = http.createServer(unauthApp);
      await registerRoutes(unauthServer, unauthApp);
      
      const response = await request(unauthApp)
        .post("/api/onboarding/generate-templates")
        .send({
          answers: {},
          options: { includeFaq: true, includePolicy: true, includeDelivery: true, includeReturns: true },
        });

      expect(response.status).toBe(403);
    });
  });
});
